# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
 #   my_first_services:
  #      class: Nalbashgroup\NalbashBundle\Services\MyFirstServices
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
